//! Protobuf / Connect RPC interface for Mangle.
//!
//! This crate contains:
//!
//! - the canonical, schema-less encoding of Mangle facts
//!   ([`pb::Value`](pb::value::Value), [`pb::Fact`], [`pb::FactBatch`]) —
//!   see `crates/mangle-server/RPC_DESIGN.md` for the design;
//! - the [`pb::MangleService`] trait (Connect RPC, generated by
//!   connectrpc-build on top of the buffa runtime);
//! - conversions between the wire types and `mangle_common::Value` /
//!   `Vec<Value>` tuples, in both row and columnar form, for owned and
//!   zero-copy view inputs.
//!
//! The server speaks only the canonical encoding; typed per-program
//! overlays (generated `.proto` files where each predicate is a message)
//! transcode to/from this form client-side.

/// Generated protobuf message types and the `MangleService` trait.
pub mod pb {
    connectrpc::include_generated!();
}

mod convert;
mod convert_view;

pub use convert::{
    batch_from_rows, fact_from_row, fact_to_proto, rows_from_batch, value_from_proto,
    value_to_proto,
};
pub use convert_view::{fact_from_view, rows_from_batch_view, value_from_view};
