/* mangle-ffi: C ABI for the Mangle logic-programming engine.
 *
 * This header is auto-generated by cbindgen from the Rust sources in
 * crates/mangle-ffi/src/. Do not edit by hand. Regenerate via `cargo build
 * -p mangle-ffi`; CI fails if the committed copy drifts from a regen.
 *
 * ABI contract:
 *   - Functions returning `int32_t` use 0 = success, nonzero = error.
 *     On nonzero, call `mangle_last_error` for a formatted message
 *     (added in milestone M1; M0 only defines the buffer plumbing).
 *   - `MangleBuffer` outputs are caller-owned: free with `mangle_buffer_free`.
 *   - All entry points are panic-safe (Rust panics are caught and converted
 *     to errors, never propagated across the FFI boundary).
 */

#ifndef MANGLE_FFI_H
#define MANGLE_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * Opaque value handle. The layout is internal; consumers may only
 * inspect a `MangleVal` through the `mangle_val_*` accessor functions
 * declared below. Lifetime: a handle is borrowed from its producer
 * (`MangleValBuilder` today, cursor row buffers from M4 onwards) and
 * must not outlive it.
 */
typedef struct MangleVal MangleVal;


/**
 * FFI status: success.
 */
#define MANGLE_OK 0

/**
 * FFI status: generic error. The thread-local error slot (read via
 * `mangle_last_error`) holds the formatted message.
 */
#define MANGLE_ERR -1

/**
 * FFI status: an argument was invalid (null pointer, malformed UTF-8,
 * wrong kind for an accessor, etc.).
 */
#define MANGLE_ERR_INVALID_ARG -2

/**
 * FFI status: the engine has no rules loaded. Returned by query and
 * snapshot operations on a Fresh engine. Reserved for M2.
 */
#define MANGLE_ERR_NO_RULES -3

/**
 * FFI status: the cursor's engine generation no longer matches the
 * engine's current generation (rules reloaded, or a panic poisoned the
 * engine). The cursor handle is still safe to free but produces no
 * more rows. Reserved for M4.
 */
#define MANGLE_ERR_CURSOR_INVALIDATED -4

/**
 * FFI status: derivation-tree introspection was requested but the
 * engine was constructed with `enable_provenance = 0`. Reserved for M9.
 */
#define MANGLE_ERR_NO_PROVENANCE -5

/**
 * FFI status: a fact lookup (e.g. for derivation tree) found no
 * matching tuple. Reserved for M9.
 */
#define MANGLE_ERR_FACT_NOT_FOUND -6

/**
 * FFI status: a parse failure in rule, query, or fact-atom input.
 * Reserved for M2 onwards.
 */
#define MANGLE_ERR_PARSE -7

/**
 * FFI status: an entry point caught a panic. If the entry point took
 * an engine, that engine is now *poisoned* — subsequent operations on
 * it will short-circuit to this same code. Recovery: free the engine
 * and create a fresh one.
 */
#define MANGLE_ERR_PANIC -8

/**
 * FFI status: the named relation is not declared in the loaded
 * program. Catches predicate-name typos at the entry point instead
 * of silently returning an empty cursor or an empty `.mgr` blob.
 * Introduced in M8.
 */
#define MANGLE_ERR_UNKNOWN_RELATION -9

/**
 * Compression mode: no compression.
 */
#define MANGLE_COMPRESSION_NONE 0

/**
 * Compression mode: gzip.
 */
#define MANGLE_COMPRESSION_GZIP 1

/**
 * Compression mode: zstd. Reserved; **not currently supported on the
 * write side** — `ruzstd` is decode-only and we don't pull in a
 * libzstd dependency just for this. The read side accepts
 * zstd-compressed `.mgr` input via `ruzstd::decoding::StreamingDecoder`,
 * so consumers that only need to *load* zstd blobs continue to work.
 */
#define MANGLE_COMPRESSION_ZSTD 2

/**
 * Value kind: `Null`.
 */
#define MANGLE_VAL_NULL 0

/**
 * Value kind: `Number(i64)`.
 */
#define MANGLE_VAL_NUMBER 1

/**
 * Value kind: `Float(f64)`.
 */
#define MANGLE_VAL_FLOAT 2

/**
 * Value kind: `String`.
 */
#define MANGLE_VAL_STRING 3

/**
 * Value kind: `Name` (a `/`-prefixed identifier).
 */
#define MANGLE_VAL_NAME 4

/**
 * Value kind: `Time` (i64 nanoseconds since Unix epoch).
 */
#define MANGLE_VAL_TIME 5

/**
 * Value kind: `Duration` (i64 nanoseconds).
 */
#define MANGLE_VAL_DURATION 6

/**
 * Value kind: `Compound` (list, pair, map, or struct).
 */
#define MANGLE_VAL_COMPOUND 7

/**
 * Compound subkind: ordered sequence.
 */
#define MANGLE_COMPOUND_LIST 0

/**
 * Compound subkind: two-element pair.
 */
#define MANGLE_COMPOUND_PAIR 1

/**
 * Compound subkind: keyed map (flat `[k0, v0, k1, v1, ...]`).
 */
#define MANGLE_COMPOUND_MAP 2

/**
 * Compound subkind: struct (flat `[k0, v0, k1, v1, ...]` with name keys).
 */
#define MANGLE_COMPOUND_STRUCT 3

/**
 * Query result cursor.
 */
typedef struct MangleCursor MangleCursor;

/**
 * Opaque engine handle.
 *
 * The flag and counter fields are `pub(crate)` so the
 * `panic_boundary!` macro can read/mutate them directly; consumers see
 * only an opaque pointer through the C ABI.
 */
typedef struct MangleEngine MangleEngine;

/**
 * Arena owning a set of `Value`s constructed via the `build_*` entry
 * points. Hands out `*const MangleVal` handles that are valid until
 * the builder is freed.
 */
typedef struct MangleValBuilder MangleValBuilder;

/**
 * A heap-allocated byte buffer owned by the caller.
 *
 * Returned by FFI entry points that produce variable-length output. The
 * caller must release it with [`mangle_buffer_free`]. A zeroed
 * `MangleBuffer` (all fields 0/null) is the canonical "empty / released"
 * state; freeing it is a no-op.
 */
typedef struct MangleBuffer {
  uint8_t *data;
  uintptr_t len;
  uintptr_t cap;
} MangleBuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Write the library's semantic version as a UTF-8 string into `out`.
 *
 * Always succeeds unless `out` is null. The returned buffer is owned
 * by the caller and must be released with [`mangle_buffer_free`].
 *
 * # Safety
 * `out` must be non-null and point to a writable [`MangleBuffer`].
 */
int32_t mangle_version(struct MangleBuffer *out);

/**
 * Release a [`MangleBuffer`] previously produced by the library.
 *
 * Safe to call with a null pointer or a zeroed/empty buffer (both
 * no-ops). After return, the buffer's fields are zeroed so a subsequent
 * double-free is also a no-op.
 *
 * # Safety
 * If `buf` is non-null, it must point to a buffer that was produced by
 * this library and has not been freed. The buffer's `data`/`len`/`cap`
 * fields must not have been modified by the caller.
 */
void mangle_buffer_free(struct MangleBuffer *buf);

/**
 * Construct a new value builder. Returns null on allocation failure
 * (which is currently unreachable, but the C ABI consumer should still
 * check). Release with [`mangle_val_builder_free`].
 *
 * # Safety
 * Safe to call from any context; the `unsafe` marker is for ABI
 * consistency with the other entry points in this crate.
 */
struct MangleValBuilder *mangle_val_builder_new(void);

/**
 * Release a builder. All handles previously returned by `build_*`
 * against this builder become invalid; using them after this call is
 * UB. Passing null is a no-op.
 *
 * # Safety
 * If `b` is non-null, it must point to a builder previously returned
 * by [`mangle_val_builder_new`] that has not already been freed.
 */
void mangle_val_builder_free(struct MangleValBuilder *b);

/**
 * Build a `Null` value.
 *
 * # Safety
 * `b` must be a live builder.
 */
const MangleVal *mangle_val_build_null(struct MangleValBuilder *b);

/**
 * Build a `Number` value from an `i64`.
 *
 * # Safety
 * `b` must be a live builder.
 */
const MangleVal *mangle_val_build_i64(struct MangleValBuilder *b, int64_t n);

/**
 * Build a `Float` value from an `f64`.
 *
 * # Safety
 * `b` must be a live builder.
 */
const MangleVal *mangle_val_build_f64(struct MangleValBuilder *b, double f);

/**
 * Build a `Time` value from i64 nanoseconds since the Unix epoch.
 *
 * # Safety
 * `b` must be a live builder.
 */
const MangleVal *mangle_val_build_time_ns(struct MangleValBuilder *b, int64_t nanos);

/**
 * Build a `Duration` value from i64 nanoseconds.
 *
 * # Safety
 * `b` must be a live builder.
 */
const MangleVal *mangle_val_build_duration_ns(struct MangleValBuilder *b, int64_t nanos);

/**
 * Build a `String` value from a UTF-8 byte slice. Returns null and
 * sets last_error on invalid UTF-8.
 *
 * # Safety
 * `b` must be live. `s` must point to `len` readable bytes (or be null
 * with `len == 0`).
 */
const MangleVal *mangle_val_build_string(struct MangleValBuilder *b,
                                         const uint8_t *s,
                                         uintptr_t len);

/**
 * Build a `Name` value from a UTF-8 byte slice.
 *
 * Mangle name constants must start with `/`; otherwise this returns
 * null and populates `last_error`. (Matches mangle-py's `PyName::new`
 * contract.)
 *
 * # Safety
 * `b` must be live. `s` must point to `len` readable bytes (or be null
 * with `len == 0`).
 */
const MangleVal *mangle_val_build_name(struct MangleValBuilder *b, const uint8_t *s, uintptr_t len);

/**
 * Build a compound value (`List`, `Pair`, `Map`, or `Struct`) by
 * cloning the given element handles into a new `Value::Compound`.
 *
 * `subkind` selects the compound kind via the `MANGLE_COMPOUND_*`
 * constants. For `Map` and `Struct`, `elems` is a flat `[k0, v0, k1,
 * v1, ...]` sequence and `n` is the total entry count (so `n` must be
 * even).
 *
 * Element handles must point to values living in the same builder (or
 * in any other producer with stable lifetime through this call); they
 * are cloned, not aliased, so the originals can be freed independently
 * of the resulting compound.
 *
 * Returns null and sets last_error on bad subkind, bad element
 * pointer, or odd `n` for map/struct.
 *
 * # Safety
 * `b` must be live. `elems` must point to `n` readable `*const MangleVal`
 * entries; each non-null entry must reference a live value.
 */
const MangleVal *mangle_val_build_compound(struct MangleValBuilder *b,
                                           int32_t subkind,
                                           const MangleVal *const *elems,
                                           uintptr_t n);

/**
 * Open a cursor over the tuples matching `query`.
 *
 * `query` is a Mangle atom: a bare predicate name like `reachable`,
 * or `pred(arg1, ...)` with constants used as equality filters and
 * uppercase identifiers acting as wildcards. See
 * [`crate::query::parse_query_lenient`] for the exact syntax.
 *
 * Returns [`MANGLE_OK`] on success and writes the cursor pointer to
 * `*out`. Returns [`MANGLE_ERR_NO_RULES`] if the engine has no
 * program loaded, [`MANGLE_ERR_PARSE`] for a malformed query, or
 * [`MANGLE_ERR`] if the named relation does not exist in the store.
 *
 * The cursor must be released with [`mangle_cursor_free`] (which is
 * safe to call in any order with respect to engine free). Calling
 * [`mangle_cursor_next`] requires the engine to still be alive.
 *
 * # Safety
 * `engine` must be a live handle. `query` must point to `query_len`
 * readable UTF-8 bytes (or be null with `query_len == 0`). `out` must
 * be non-null and point to writable storage for a `*mut MangleCursor`.
 */
int32_t mangle_query(struct MangleEngine *engine,
                     const uint8_t *query,
                     uintptr_t query_len,
                     struct MangleCursor **out);

/**
 * Advance the cursor to the next row.
 *
 * Returns:
 *   - [`MANGLE_OK`] (0) when a row was produced; access columns via
 *     [`mangle_cursor_arity`] and [`mangle_cursor_col`].
 *   - `1` when the cursor has reached end-of-stream. Further calls
 *     also return `1`.
 *   - [`MANGLE_ERR_CURSOR_INVALIDATED`] when the engine has been
 *     reloaded or poisoned since the cursor was opened. The cursor
 *     handle is still safe to free but yields no more rows.
 *   - [`MANGLE_ERR_INVALID_ARG`] when `cursor` is null.
 *
 * # Safety
 * `cursor` must be a live cursor. The engine that produced it must be
 * alive at the time of the call (it is dereferenced to read the
 * generation counter); calling this after `mangle_engine_free` on
 * the producing engine is undefined behavior.
 */
int32_t mangle_cursor_next(struct MangleCursor *cursor);

/**
 * Report the arity (column count) of the current row.
 *
 * Returns the column count when a row is loaded (after a successful
 * [`mangle_cursor_next`]). Returns `0` when no row is loaded
 * (before first call or after end-of-stream). Returns `-1` if
 * `cursor` is null.
 *
 * # Safety
 * `cursor` must be null or a live cursor.
 */
int32_t mangle_cursor_arity(struct MangleCursor *cursor);

/**
 * Borrowed handle to the column at `col_idx` in the current row.
 *
 * Returns null if `cursor` is null, no row is loaded, or the index is
 * out of range. The returned handle borrows from the cursor's
 * current-row buffer and is valid until the next call to
 * [`mangle_cursor_next`] or [`mangle_cursor_free`] on this cursor.
 *
 * # Safety
 * `cursor` must be null or a live cursor.
 */
const MangleVal *mangle_cursor_col(struct MangleCursor *cursor, uint32_t col_idx);

/**
 * Release a cursor.
 *
 * Safe to call on null. Safe to call regardless of the producing
 * engine's state (the cursor's row data is owned, not borrowed; this
 * function does not dereference the stored engine pointer).
 *
 * # Safety
 * If `cursor` is non-null, it must point to a cursor previously
 * returned by [`mangle_query`] that has not already been freed.
 */
void mangle_cursor_free(struct MangleCursor *cursor);

/**
 * Emit the derivation tree for a given fact as JSON.
 *
 * The fact is parsed as a Mangle atom — same syntax as queries (see
 * `mangle_query`) — but variables aren't allowed: the fact must be
 * fully ground.
 *
 * Requires the engine was constructed with `enable_provenance = 1`.
 * Returns:
 * - [`MANGLE_OK`] on success; JSON buffer owned by caller.
 * - [`MANGLE_ERR_NO_RULES`] when no program is loaded.
 * - [`MANGLE_ERR_NO_PROVENANCE`] when the engine was built without
 *   provenance.
 * - [`MANGLE_ERR_PARSE`] for a malformed atom or a variable arg.
 * - [`MANGLE_ERR_FACT_NOT_FOUND`] when the fact has no recorded
 *   derivations (EDB facts with no IDB consumers may not appear at
 *   all in the provenance index; user typos likewise).
 * - [`MANGLE_ERR_INVALID_ARG`] for null pointers.
 *
 * `max_depth` is the maximum nesting depth of the returned tree.
 * Use `0xFFFF_FFFF` (`UINT32_MAX`) for unlimited.
 *
 * # Safety
 * `engine` must be a live handle. `fact` must point to `len`
 * readable UTF-8 bytes. `out` must be non-null.
 */
int32_t mangle_derivation_tree(struct MangleEngine *engine,
                               const uint8_t *fact,
                               uintptr_t len,
                               uint32_t max_depth,
                               struct MangleBuffer *out);

/**
 * Construct a new engine.
 *
 * `enable_provenance` is nonzero to record derivation provenance during
 * rule evaluation (M9 surface); zero disables it. The flag is captured
 * here and consulted when rules are loaded.
 *
 * On success, writes the engine pointer to `*out` and returns
 * [`MANGLE_OK`]. The caller owns the handle and must release it with
 * [`mangle_engine_free`].
 *
 * # Safety
 * `out` must be non-null and point to writable storage for a
 * `*mut MangleEngine`.
 */
int32_t mangle_engine_new(int32_t enable_provenance, struct MangleEngine **out);

/**
 * Release an engine produced by [`mangle_engine_new`].
 *
 * Safe to call on a null pointer or a poisoned engine. After return,
 * the pointer must not be used again. The drop is wrapped in
 * `catch_unwind` so an internal panic during drop cannot propagate
 * across the FFI boundary; any panic message is recorded as the
 * thread-local error.
 *
 * # Safety
 * If `engine` is non-null, it must point to a handle previously
 * produced by [`mangle_engine_new`] that has not already been freed.
 */
void mangle_engine_free(struct MangleEngine *engine);

/**
 * Compile and execute one or more Mangle source units, replacing any
 * previously loaded program.
 *
 * `sources` is an array of `n_sources` pointers; `lens` parallels it
 * with the byte length of each source. Each source is treated as
 * UTF-8.
 *
 * On success, returns [`MANGLE_OK`] and bumps the engine's generation
 * counter (any cursors opened against the previous generation will
 * refuse subsequent reads). On parse / type-check / evaluation
 * failure, the engine's previous state is preserved unchanged and a
 * nonzero status is returned with the formatted error available via
 * [`mangle_last_error`].
 *
 * # Safety
 * `engine` must be a live handle from [`mangle_engine_new`].
 * `sources` and `lens` must point to readable arrays of `n_sources`
 * elements; each `sources[i]` must point to `lens[i]` readable bytes
 * of UTF-8.
 */
int32_t mangle_load_rules(struct MangleEngine *engine,
                          const uint8_t *const *sources,
                          const uintptr_t *lens,
                          uintptr_t n_sources);

/**
 * Insert a tuple as a fact in the named relation.
 *
 * `tuple` is an array of `arity` borrowed `MangleVal` handles. The
 * values are cloned into the engine's store; the source handles
 * remain owned by their producer (typically a [`MangleValBuilder`]).
 *
 * On success, `*added_out` (if non-null) is set to 1 when the tuple
 * was new and 0 when the relation already contained it. The store's
 * scan-visible set is updated atomically: subsequent `mangle_query`
 * calls see the new tuple.
 *
 * **IDB relations are not re-derived.** Inserting a tuple into a
 * relation that is the head of one or more rules does not cause
 * those rules to fire on the new fact. To re-evaluate the IDB,
 * reload the rules with [`mangle_load_rules`]. This mirrors mangle-py
 * (`PyProgram::insert`).
 *
 * Returns [`MANGLE_OK`] on success, [`MANGLE_ERR_NO_RULES`] when no
 * program is loaded, [`MANGLE_ERR_INVALID_ARG`] for null/invalid
 * inputs, or [`MANGLE_ERR`] for a store-level failure.
 *
 * # Safety
 * `engine` must be a live handle. `relation` must point to
 * `relation_len` readable UTF-8 bytes. `tuple` must point to `arity`
 * readable `*const MangleVal` entries; each entry must be a live
 * handle. `added_out` is nullable.
 */
int32_t mangle_insert_fact(struct MangleEngine *engine,
                           const uint8_t *relation,
                           uintptr_t relation_len,
                           const MangleVal *const *tuple,
                           uintptr_t arity,
                           int32_t *added_out);

/**
 * Retract a tuple from the named relation.
 *
 * `*found_out` (if non-null) is set to 1 if the tuple was present and
 * removed, 0 otherwise. Operates on the stable set; no merge_deltas
 * is needed.
 *
 * Like insert, IDB relations are not automatically reconciled — a
 * retracted EDB fact whose absence would invalidate derived facts
 * leaves stale IDB tuples in place until rules are reloaded.
 *
 * # Safety
 * Same as [`mangle_insert_fact`].
 */
int32_t mangle_retract_fact(struct MangleEngine *engine,
                            const uint8_t *relation,
                            uintptr_t relation_len,
                            const MangleVal *const *tuple,
                            uintptr_t arity,
                            int32_t *found_out);

/**
 * Copy the current thread-local error message into `out` and clear it.
 *
 * Returns [`MANGLE_OK`] regardless of whether an error was set; the
 * resulting buffer will be empty (zero-length, possibly null `data`)
 * when there was nothing to report. Calling this in a no-error state
 * is the canonical way to check + clear.
 *
 * # Safety
 * `out` must be non-null and point to a writable [`MangleBuffer`].
 */
int32_t mangle_last_error(struct MangleBuffer *out);

/**
 * Bulk-load facts from a `.mgr` byte slice into the engine.
 *
 * `bytes` is a SimpleRow byte stream as produced by
 * `mangle_db::simplerow::write_simple_row` (M7), optionally
 * compressed with gzip or zstd (auto-detected via magic bytes).
 *
 * `source_name` is a human-readable identifier (e.g. a file path)
 * included verbatim in error messages. May be empty.
 *
 * On success, returns [`MANGLE_OK`] and writes the number of
 * inserted tuples (including duplicates) into `*n_inserted_out` if
 * non-null. The store's scan-visible set is updated atomically;
 * subsequent queries see all loaded tuples. Returns
 * [`MANGLE_ERR_NO_RULES`] when the engine has no program loaded
 * (load rules first), [`MANGLE_ERR_PARSE`] when the byte stream
 * isn't a valid `.mgr`, [`MANGLE_ERR_INVALID_ARG`] for null pointers
 * or invalid UTF-8 in `source_name`, or [`MANGLE_ERR`] for other
 * failures (decompression error, store-level insert failure).
 *
 * IDB relations are not re-derived — see [`mangle_insert_fact`] for
 * the same caveat.
 *
 * # Safety
 * `engine` must be a live handle. `bytes` must point to `len`
 * readable bytes (or be null with `len == 0`). `source_name` must
 * point to `name_len` readable UTF-8 bytes (or be null with
 * `name_len == 0`). `n_inserted_out` is nullable.
 */
int32_t mangle_load_facts_mgr(struct MangleEngine *engine,
                              const uint8_t *bytes,
                              uintptr_t len,
                              const uint8_t *source_name,
                              uintptr_t name_len,
                              uintptr_t *n_inserted_out);

/**
 * Encode every relation in the engine's store as a single SimpleRow
 * `.mgr` blob, optionally compressed.
 *
 * Use for "Save Project" — write the resulting buffer to `facts.mgr`
 * (or `facts.mgr.gz` if `compression == MANGLE_COMPRESSION_GZIP`).
 *
 * Returns [`MANGLE_OK`] on success; the resulting buffer is owned by
 * the caller and must be freed with [`mangle_buffer_free`]. Returns
 * [`MANGLE_ERR_NO_RULES`] when no program is loaded,
 * [`MANGLE_ERR_INVALID_ARG`] for null `out` or an unsupported
 * compression mode (currently `MANGLE_COMPRESSION_ZSTD`), or
 * [`MANGLE_ERR`] for store-side or encoding failures.
 *
 * # Safety
 * `engine` must be a live handle. `out` must be non-null and point to
 * a writable [`MangleBuffer`].
 */
int32_t mangle_save_facts_mgr(struct MangleEngine *engine,
                              int32_t compression,
                              struct MangleBuffer *out);

/**
 * Encode a single named relation as a SimpleRow `.mgr` blob,
 * optionally compressed. Useful for per-relation backups or exports.
 *
 * Returns [`MANGLE_ERR`] if the relation does not exist in the store;
 * other error codes match [`mangle_save_facts_mgr`].
 *
 * # Safety
 * `engine` must be a live handle. `relation` must point to
 * `relation_len` readable UTF-8 bytes. `out` must be non-null.
 */
int32_t mangle_save_relation_mgr(struct MangleEngine *engine,
                                 const uint8_t *relation,
                                 uintptr_t relation_len,
                                 int32_t compression,
                                 struct MangleBuffer *out);

/**
 * Run a query and encode the matching tuples as a SimpleRow `.mgr`
 * blob under the caller-supplied relation name `out_relation`.
 *
 * Useful for "Export Query Result" — the user types `route("GET",
 * Path)`, the workbench produces a downloadable `.mgr` file where
 * the matching tuples live under a relation named e.g.
 * `get_routes`. The output relation name is independent of the
 * queried predicate, so it can be anything the consumer wants.
 *
 * Query syntax matches [`mangle_query`].
 *
 * # Safety
 * `engine` must be a live handle. `query` must point to `query_len`
 * readable UTF-8 bytes. `out_relation` must point to
 * `out_relation_len` readable UTF-8 bytes (must be non-empty). `out`
 * must be non-null.
 */
int32_t mangle_query_dump_mgr(struct MangleEngine *engine,
                              const uint8_t *query,
                              uintptr_t query_len,
                              const uint8_t *out_relation,
                              uintptr_t out_relation_len,
                              int32_t compression,
                              struct MangleBuffer *out);

/**
 * Emit the engine's schema as a JSON document.
 *
 * Shape:
 * ```json
 * {
 *   "predicates": [
 *     { "name": "edge", "arity": 2, "type_args": null, "kind": "edb" },
 *     { "name": "reachable", "arity": 2, "type_args": null, "kind": "idb" }
 *   ],
 *   "rules": [
 *     { "rule_id": 0, "head": "reachable", "body": ["edge"] },
 *     { "rule_id": 1, "head": "reachable", "body": ["edge", "reachable"] }
 *   ]
 * }
 * ```
 *
 * `kind` is `"edb"` or `"idb"` based on whether the predicate has
 * any defining rules. `type_args` will populate in a later milestone
 * when the Ir's `Decl.bounds` walker is wired up; for now it's
 * `null`.
 *
 * Returns [`MANGLE_OK`] on success; the buffer is owned by the
 * caller and must be released with `mangle_buffer_free`. Returns
 * [`MANGLE_ERR_NO_RULES`] when the engine has no program loaded, or
 * [`MANGLE_ERR_INVALID_ARG`] for null `out`.
 *
 * # Safety
 * `engine` must be a live handle. `out` must be non-null.
 */
int32_t mangle_schema_snapshot(struct MangleEngine *engine, struct MangleBuffer *out);

/**
 * Emit the sorted list of declared predicate names as a JSON array.
 *
 * Cheap alternative to [`mangle_schema_snapshot`] when you only need
 * the picker UI's relation dropdown — no arity, no rule edges, just
 * the names.
 *
 * # Safety
 * `engine` must be a live handle. `out` must be non-null.
 */
int32_t mangle_relation_names(struct MangleEngine *engine, struct MangleBuffer *out);

/**
 * Report the kind tag of a value.
 *
 * Returns one of the `MANGLE_VAL_*` constants. Returns `-1` if `v` is
 * null or accessing it panics.
 *
 * # Safety
 * If `v` is non-null, it must point to a live `MangleVal` borrowed
 * from a producer (builder or cursor row) that has not been freed.
 */
int32_t mangle_val_kind(const MangleVal *v);

/**
 * Extract an `i64` from a `Number`, `Time`, or `Duration` value.
 *
 * Returns [`MANGLE_OK`] on success. Returns [`MANGLE_ERR_INVALID_ARG`]
 * for null inputs and [`MANGLE_ERR`] for a wrong-kind value (with the
 * last_error slot populated).
 *
 * # Safety
 * `v` and `out` must be non-null and live.
 */
int32_t mangle_val_as_i64(const MangleVal *v, int64_t *out);

/**
 * Extract an `f64` from a `Float` value.
 *
 * # Safety
 * `v` and `out` must be non-null and live.
 */
int32_t mangle_val_as_f64(const MangleVal *v, double *out);

/**
 * Copy the textual content of a `String` or `Name` value into `out`.
 *
 * For a `Name`, the leading `/` is **kept** — consumers that want it
 * stripped should slice the buffer after the call. (Keeping it
 * preserves the round-trip property: `build_name(as_str(name))` is the
 * identity.)
 *
 * # Safety
 * `v` and `out` must be non-null and live.
 */
int32_t mangle_val_as_str(const MangleVal *v, struct MangleBuffer *out);

/**
 * Report the compound subkind of a compound value.
 *
 * # Safety
 * `v` and `subkind_out` must be non-null and live.
 */
int32_t mangle_val_compound_kind(const MangleVal *v, int32_t *subkind_out);

/**
 * Report the number of items (for `List`/`Pair`) or pairs (for
 * `Map`/`Struct`) in a compound value.
 *
 * For maps and structs, the underlying flat vector has `2*N` entries
 * for `N` pairs; this function returns `N`, not `2*N`.
 *
 * # Safety
 * `v` and `out` must be non-null and live.
 */
int32_t mangle_val_compound_len(const MangleVal *v, uintptr_t *out);

/**
 * Borrowed handle to a compound element at the given linear index.
 *
 * Use this for `List`/`Pair` values. For `Map`/`Struct`, use
 * [`mangle_val_compound_kv`] instead — the indexing semantics differ
 * (pair index vs. flat index).
 *
 * Returns `null` if `v` is null, not a compound, or the index is out
 * of range. The returned handle borrows from the same producer as
 * `v`; do not outlive it.
 *
 * # Safety
 * `v` must be null or a live handle.
 */
const MangleVal *mangle_val_compound_get(const MangleVal *v, uintptr_t index);

/**
 * Borrowed handles to the key and value at a given pair index in a
 * `Map` or `Struct` value.
 *
 * `pair_index` is in `0..N` where `N` is `mangle_val_compound_len`.
 * The underlying flat vector positions are `2 * pair_index` (key) and
 * `2 * pair_index + 1` (value).
 *
 * # Safety
 * `v`, `key_out`, and `val_out` must be non-null and live.
 */
int32_t mangle_val_compound_kv(const MangleVal *v,
                               uintptr_t pair_index,
                               const MangleVal **key_out,
                               const MangleVal **val_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MANGLE_FFI_H */
