/* mangle-ffi: C ABI for the Mangle logic-programming engine.
 *
 * This header is auto-generated by cbindgen from the Rust sources in
 * crates/mangle-ffi/src/. Do not edit by hand. Regenerate via `cargo build
 * -p mangle-ffi`; CI fails if the committed copy drifts from a regen.
 *
 * ABI contract:
 *   - Functions returning `int32_t` use 0 = success, nonzero = error.
 *     On nonzero, call `mangle_last_error` for a formatted message
 *     (added in milestone M1; M0 only defines the buffer plumbing).
 *   - `MangleBuffer` outputs are caller-owned: free with `mangle_buffer_free`.
 *   - All entry points are panic-safe (Rust panics are caught and converted
 *     to errors, never propagated across the FFI boundary).
 */

#ifndef MANGLE_FFI_H
#define MANGLE_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * FFI status: success.
 */
#define MANGLE_OK 0

/**
 * FFI status: an argument was invalid (null pointer, malformed UTF-8,
 * wrong kind for an accessor, etc.).
 */
#define MANGLE_ERR_INVALID_ARG -2

/**
 * A heap-allocated byte buffer owned by the caller.
 *
 * Returned by FFI entry points that produce variable-length output. The
 * caller must release it with [`mangle_buffer_free`]. A zeroed
 * `MangleBuffer` (all fields 0/null) is the canonical "empty / released"
 * state; freeing it is a no-op.
 */
typedef struct MangleBuffer {
  uint8_t *data;
  uintptr_t len;
  uintptr_t cap;
} MangleBuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

extern int32_t c_smoke_run(void);

/**
 * Write the library's semantic version as a UTF-8 string into `out`.
 *
 * Always succeeds unless `out` is null. The returned buffer is owned by
 * the caller and must be released with [`mangle_buffer_free`].
 *
 * # Safety
 * `out` must be non-null and point to a writable [`MangleBuffer`].
 */
int32_t mangle_version(struct MangleBuffer *out);

/**
 * Release a [`MangleBuffer`] previously produced by the library.
 *
 * Safe to call with a null pointer or a zeroed/empty buffer (both
 * no-ops). After return, the buffer's fields are zeroed so a subsequent
 * double-free is also a no-op.
 *
 * # Safety
 * If `buf` is non-null, it must point to a buffer that was produced by
 * this library and has not been freed. The buffer's `data`/`len`/`cap`
 * fields must not have been modified by the caller.
 */
void mangle_buffer_free(struct MangleBuffer *buf);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MANGLE_FFI_H */
