/* mangle-ffi: C ABI for the Mangle logic-programming engine.
 *
 * This header is auto-generated by cbindgen from the Rust sources in
 * crates/mangle-ffi/src/. Do not edit by hand. Regenerate via `cargo build
 * -p mangle-ffi`; CI fails if the committed copy drifts from a regen.
 *
 * ABI contract:
 *   - Functions returning `int32_t` use 0 = success, nonzero = error.
 *     On nonzero, call `mangle_last_error` for a formatted message
 *     (added in milestone M1; M0 only defines the buffer plumbing).
 *   - `MangleBuffer` outputs are caller-owned: free with `mangle_buffer_free`.
 *   - All entry points are panic-safe (Rust panics are caught and converted
 *     to errors, never propagated across the FFI boundary).
 */

#ifndef MANGLE_FFI_H
#define MANGLE_FFI_H

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include <stdint.h>
#include <stddef.h>

/**
 * FFI status: success.
 */
#define MANGLE_OK 0

/**
 * FFI status: generic error. The thread-local error slot (read via
 * `mangle_last_error`) holds the formatted message.
 */
#define MANGLE_ERR -1

/**
 * FFI status: an argument was invalid (null pointer, malformed UTF-8,
 * wrong kind for an accessor, etc.).
 */
#define MANGLE_ERR_INVALID_ARG -2

/**
 * FFI status: the engine has no rules loaded. Returned by query and
 * snapshot operations on a Fresh engine. Reserved for M2.
 */
#define MANGLE_ERR_NO_RULES -3

/**
 * FFI status: the cursor's engine generation no longer matches the
 * engine's current generation (rules reloaded, or a panic poisoned the
 * engine). The cursor handle is still safe to free but produces no
 * more rows. Reserved for M4.
 */
#define MANGLE_ERR_CURSOR_INVALIDATED -4

/**
 * FFI status: derivation-tree introspection was requested but the
 * engine was constructed with `enable_provenance = 0`. Reserved for M9.
 */
#define MANGLE_ERR_NO_PROVENANCE -5

/**
 * FFI status: a fact lookup (e.g. for derivation tree) found no
 * matching tuple. Reserved for M9.
 */
#define MANGLE_ERR_FACT_NOT_FOUND -6

/**
 * FFI status: a parse failure in rule, query, or fact-atom input.
 * Reserved for M2 onwards.
 */
#define MANGLE_ERR_PARSE -7

/**
 * FFI status: an entry point caught a panic. If the entry point took
 * an engine, that engine is now *poisoned* — subsequent operations on
 * it will short-circuit to this same code. Recovery: free the engine
 * and create a fresh one.
 */
#define MANGLE_ERR_PANIC -8

/**
 * Opaque engine handle.
 *
 * The `poisoned` flag is `pub(crate)` so the `panic_boundary` macro can
 * read and set it directly across module boundaries; consumers see only
 * an opaque pointer.
 */
typedef struct MangleEngine MangleEngine;

/**
 * A heap-allocated byte buffer owned by the caller.
 *
 * Returned by FFI entry points that produce variable-length output. The
 * caller must release it with [`mangle_buffer_free`]. A zeroed
 * `MangleBuffer` (all fields 0/null) is the canonical "empty / released"
 * state; freeing it is a no-op.
 */
typedef struct MangleBuffer {
  uint8_t *data;
  uintptr_t len;
  uintptr_t cap;
} MangleBuffer;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Write the library's semantic version as a UTF-8 string into `out`.
 *
 * Always succeeds unless `out` is null. The returned buffer is owned
 * by the caller and must be released with [`mangle_buffer_free`].
 *
 * # Safety
 * `out` must be non-null and point to a writable [`MangleBuffer`].
 */
int32_t mangle_version(struct MangleBuffer *out);

/**
 * Release a [`MangleBuffer`] previously produced by the library.
 *
 * Safe to call with a null pointer or a zeroed/empty buffer (both
 * no-ops). After return, the buffer's fields are zeroed so a subsequent
 * double-free is also a no-op.
 *
 * # Safety
 * If `buf` is non-null, it must point to a buffer that was produced by
 * this library and has not been freed. The buffer's `data`/`len`/`cap`
 * fields must not have been modified by the caller.
 */
void mangle_buffer_free(struct MangleBuffer *buf);

/**
 * Construct a new engine.
 *
 * `enable_provenance` is nonzero to record derivation provenance during
 * rule evaluation (M9 surface); zero disables it. The flag is captured
 * here and consulted later when rules are loaded.
 *
 * On success, writes the engine pointer to `*out` and returns
 * [`MANGLE_OK`]. The caller owns the handle and must release it with
 * [`mangle_engine_free`].
 *
 * # Safety
 * `out` must be non-null and point to writable storage for a
 * `*mut MangleEngine`.
 */
int32_t mangle_engine_new(int32_t enable_provenance, struct MangleEngine **out);

/**
 * Release an engine produced by [`mangle_engine_new`].
 *
 * Safe to call on a null pointer or a poisoned engine. After return,
 * the pointer must not be used again. The drop is wrapped in
 * `catch_unwind` so an internal panic during drop cannot propagate
 * across the FFI boundary; any panic message is recorded as the
 * thread-local error.
 *
 * # Safety
 * If `engine` is non-null, it must point to a handle previously
 * produced by [`mangle_engine_new`] that has not already been freed.
 */
void mangle_engine_free(struct MangleEngine *engine);

/**
 * Copy the current thread-local error message into `out` and clear it.
 *
 * Returns [`MANGLE_OK`] regardless of whether an error was set; the
 * resulting buffer will be empty (zero-length, possibly null `data`)
 * when there was nothing to report. Calling this in a no-error state
 * is the canonical way to check + clear.
 *
 * # Safety
 * `out` must be non-null and point to a writable [`MangleBuffer`].
 */
int32_t mangle_last_error(struct MangleBuffer *out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* MANGLE_FFI_H */
